// Generated by scripts/pwa/vite-sw-plugin.ts - do not edit.
// Retired: the app's worker now lives at app/sw.js. This one removes itself.
self.addEventListener('install', () => self.skipWaiting());
self.addEventListener('activate', (event) => {
  event.waitUntil(self.registration.unregister());
});
