// Generated by scripts/pwa/vite-sw-plugin.ts - do not edit.
const CACHE = 'lapline-4941c2901c7b';
const PRECACHE = ["./","assets/archivo-latin-variable-E0tuGl4L.woff2","assets/fit-parser-B4P0Tc9F.js","assets/fit-parser-Cql-qx9J.js","assets/fit-parser.worker-B_sWcdl3.js","assets/gpx-parser-BAbl8BVY.js","assets/index-BBtSFl7t.css","assets/index-Dv_1Pt4Z.js","assets/jetbrains-mono-latin-variable-B9CIFXIH.woff2","icons/apple-touch-icon.png","icons/favicon-32.png","icons/favicon.svg","icons/icon-192.png","icons/icon-512.png","icons/icon-maskable-512.png","icons/icon.svg","manifest.webmanifest"];

self.addEventListener('install', (event) => {
  event.waitUntil(
    caches.open(CACHE)
      .then((cache) => cache.addAll(PRECACHE.map((f) => new URL(f, self.registration.scope))))
      .then(() => self.skipWaiting())
  );
});

// Drops every older build's cache once this one takes over - including
// caches from before the rename, when they were prefixed 'pacebeat-'.
self.addEventListener('activate', (event) => {
  event.waitUntil(
    caches.keys()
      .then((keys) => Promise.all(keys.filter((k) => (k.startsWith('lapline-') || k.startsWith('pacebeat-')) && k !== CACHE).map((k) => caches.delete(k))))
      .then(() => self.clients.claim())
  );
});

self.addEventListener('fetch', (event) => {
  const req = event.request;
  // Same-origin GETs only - the opt-in geocoding/weather lookups (and
  // anything else cross-origin) always go straight to the network.
  if (req.method !== 'GET' || new URL(req.url).origin !== self.location.origin) return;

  // Page loads: network first so a new deploy is picked up as soon as
  // it's reachable, falling back to the cached shell when offline.
  if (req.mode === 'navigate') {
    event.respondWith(
      fetch(req).catch(() => caches.match(new URL('./', self.registration.scope), { ignoreVary: true }))
    );
    return;
  }

  // Everything else is a content-hashed build asset or a static public
  // file: cache first, filling the cache on a miss. ignoreVary: the page's
  // crossorigin module/style requests carry an Origin header the precache
  // requests didn't, which a server's "Vary: Origin" would otherwise turn
  // into a cache miss - harmless to ignore when the URL is content-hashed.
  event.respondWith(
    caches.match(req, { ignoreVary: true }).then((hit) => hit || fetch(req).then((res) => {
      if (res.ok) {
        const copy = res.clone();
        caches.open(CACHE).then((cache) => cache.put(req, copy));
      }
      return res;
    }))
  );
});
