// Generated by scripts/pwa/vite-sw-plugin.ts - do not edit.
const CACHE = 'lapline-89b94555696e';
const BASE = "/";
const APP = BASE + 'app/';
const PRECACHE = ["assets/app-BPnWvNQd.js","assets/app-CwNHDujG.css","assets/archivo-latin-variable-E0tuGl4L.woff2","assets/changelog-61uACh08.js","assets/fit-parser-B5nsFNb1.js","assets/fit-parser-Cql-qx9J.js","assets/fit-parser.worker-B_sWcdl3.js","assets/gpx-parser-DPiojK_K.js","assets/guide-critical-pace-61uACh08.js","assets/guide-garmin-fit-file-without-uploading-61uACh08.js","assets/guide-heart-rate-zones-from-fit-file-61uACh08.js","assets/guide-open-fit-file-61uACh08.js","assets/import-guides-5HExj61p.js","assets/jetbrains-mono-latin-variable-B9CIFXIH.woff2","assets/main-B8eptAsD.js","assets/main-ahmoyQV7.css","demo/index.json","demo/sample-cardio.fit","demo/sample-pool-swim.fit","demo/sample-ride.fit","demo/sample-run-easy.fit","demo/sample-run-long.fit","demo/sample-run-steady.fit","icons/apple-touch-icon.png","icons/favicon-32.png","icons/favicon.svg","icons/icon-192.png","icons/icon-512.png","icons/icon-maskable-512.png","icons/icon.svg","manifest.webmanifest","robots.txt","sitemap.xml"];

self.addEventListener('install', (event) => {
  event.waitUntil(
    caches.open(CACHE)
      .then((cache) => cache.addAll([APP, ...PRECACHE.map((f) => BASE + f)].map((f) => new URL(f, self.location.origin))))
      .then(() => self.skipWaiting())
  );
});

// Drops every older build's cache once this one takes over - including
// caches from before the rename, when they were prefixed 'pacebeat-'.
self.addEventListener('activate', (event) => {
  event.waitUntil(
    caches.keys()
      .then((keys) => Promise.all(keys.filter((k) => (k.startsWith('lapline-') || k.startsWith('pacebeat-')) && k !== CACHE).map((k) => caches.delete(k))))
      .then(() => self.clients.claim())
  );
});

self.addEventListener('fetch', (event) => {
  const req = event.request;
  // Same-origin GETs only - the opt-in geocoding/weather lookups (and
  // anything else cross-origin) always go straight to the network.
  if (req.method !== 'GET' || new URL(req.url).origin !== self.location.origin) return;

  // Page loads: network first so a new deploy is picked up as soon as
  // it's reachable, falling back to the cached shell when offline.
  if (req.mode === 'navigate') {
    event.respondWith(
      fetch(req).catch(() => caches.match(new URL(APP, self.location.origin), { ignoreVary: true }))
    );
    return;
  }

  // Everything else is a content-hashed build asset or a static public
  // file: cache first, filling the cache on a miss. ignoreVary: the page's
  // crossorigin module/style requests carry an Origin header the precache
  // requests didn't, which a server's "Vary: Origin" would otherwise turn
  // into a cache miss - harmless to ignore when the URL is content-hashed.
  event.respondWith(
    caches.match(req, { ignoreVary: true }).then((hit) => hit || fetch(req).then((res) => {
      if (res.ok) {
        const copy = res.clone();
        caches.open(CACHE).then((cache) => cache.put(req, copy));
      }
      return res;
    }))
  );
});
